"""empty message

Revision ID: 610092afac2c
Revises: 
Create Date: 2024-07-05 14:56:03.460303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610092afac2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
